package starter;


/**
* starter/Starter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from starter.idl
* Tuesday, 9 June 2015 10:05:16 o'clock CEST
*/

public interface Starter extends StarterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Starter
