package monitor;


/**
* monitor/Monitor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monitor.idl
* Dienstag, 2. Juni 2015 12:36 Uhr MESZ
*/

public interface Monitor extends MonitorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Monitor
