#!/bin/bash

nsport=20000
nsname=localhost

orbd -ORBInitialHost $nsname -ORBInitialPort $nsport &
sleep 1

java -jar Verkehrschaos.jar name=Streets nameserverport=$nsport nameserverhost=$nsname -ORBInitialHost $nsname &> /dev/null &

sleep 1
java -jar VerkehrschaosControl.jar name=Streets nameserverport=$nsport nameserverhost=$nsname -ORBInitialHost $nsname

killall java & killall orbd
