#!/bin/bash

nsport=20000
nsname=localhost

orbd -ORBInitialHost $nsname -ORBInitialPort $nsport &
sleep 1

java -jar Verkehrschaos.jar name=Streets nameserverport=$nsport nameserverhost=$nsname -ORBInitialHost $nsname &> /dev/null &

# start companys
cd VerkehrschaosTruckCompany/bin/
java verkehrschaosTruckCompany.companyStarter --name=Aldi --location=nord &
java verkehrschaosTruckCompany.companyStarter --name=Lidl --location=ost &
java verkehrschaosTruckCompany.companyStarter --name=Rewe --location=sued &
java verkehrschaosTruckCompany.companyStarter --name=Penny --location=west &

# start trucks
cd ../../VerkehrschaosTruck/bin/
java verkehrschaosTruck.truckStarter --name=Marian --company=Aldi &
java verkehrschaosTruck.truckStarter --name=Apple-Boy --company=Aldi &
java verkehrschaosTruck.truckStarter --name=Sheldon --company=Lidl &
java verkehrschaosTruck.truckStarter --name=Bane --company=Lidl &
java verkehrschaosTruck.truckStarter --name=Hans --company=Rewe &
java verkehrschaosTruck.truckStarter --name=GNU-Dad --company=Rewe &
java verkehrschaosTruck.truckStarter --name=Batman --company=Penny &
java verkehrschaosTruck.truckStarter --name=Machete --company=Penny &

cd ../../

sleep 1
java -jar VerkehrschaosControl.jar name=Streets nameserverport=$nsport nameserverhost=$nsname -ORBInitialHost $nsname

killall java & killall orbd
