package monitor;


/**
* monitor/Monitor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monitor.idl
* Tuesday, 9 June 2015 10:05:16 o'clock CEST
*/

public interface Monitor extends MonitorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Monitor
