package coordinator;


/**
* coordinator/Coordinator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from coordinator.idl
* Tuesday, 9 June 2015 10:05:16 o'clock CEST
*/

public interface Coordinator extends CoordinatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Coordinator
