package coordinator;


/**
* coordinator/Coordinator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from coordinator.idl
* Dienstag, 2. Juni 2015 17:45 Uhr MESZ
*/

public interface Coordinator extends CoordinatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Coordinator
