#!/bin/bash
if [[ "$1" != "compile-only" ]]; then
  wget http://tiserver02.cpt.haw-hamburg.de/htm/vs/ws/HAWMeter.zip
  unzip -o HAWMeter.zip
  rm -f HAWMeter.zip
  if [[ "$1" != "no-patch" ]]; then
    cp fix_bind_exception.patch HAWMeter/src/hawmetering
    cd HAWMeter/src/hawmetering
    patch < fix_bind_exception.patch
    cd ../../../
  fi
fi

# build haw meter
cd HAWMeter
javac -d build -cp src:lib/jcommon-1.0.16.jar:lib/jfreechart-1.0.13.jar src/hawmetering/HAWMetering.java

#cd HAWMeter
#java  -cp build:images:lib/jcommon-1.0.16.jar:lib/jfreechart-1.0.13.jar hawmetering.HAWMetering

