#!/bin/bash
outfolder=out
idlj -td $outfolder -f all worker.idl
idlj -td $outfolder -f all coordinator.idl
idlj -td $outfolder -f all starter.idl
idlj -td $outfolder -f all monitor.idl

cp -R out/worker/ ../projects/worker/src/worker/
cp -R out/worker/ ../projects/coordinator/src/worker/
cp -R out/worker/ ../projects/starter/src/worker/
cp -R out/worker/ ../projects/client/src/worker/

cp -R out/coordinator/ ../projects/worker/src/coordinator/
cp -R out/coordinator/ ../projects/coordinator/src/coordinator/
cp -R out/coordinator/ ../projects/starter/src/coordinator/
cp -R out/coordinator/ ../projects/client/src/coordinator/

cp -R out/starter/ ../projects/worker/src/starter/
cp -R out/starter/ ../projects/coordinator/src/starter/
cp -R out/starter/ ../projects/starter/src/starter/
cp -R out/starter/ ../projects/client/src/starter/

cp -R out/monitor/ ../projects/worker/src/monitor/
cp -R out/monitor/ ../projects/coordinator/src/monitor/
cp -R out/monitor/ ../projects/starter/src/monitor/
cp -R out/monitor/ ../projects/client/src/monitor/
