#!/bin/bash
java -cp coordinator/bin/:. main_starter.main_starter --monitor=$1 --name=$2 -ORBInitialPort 20000 -ORBInitialHost localhost
#java -cp coordinator/bin/:. main_starter.main_starter --monitor=$1 --name=$2 -ORBInitialPort 5000 -ORBInitialHost lab22
