#!/bin/bash
#java -cp client/bin/:. main_starter.main_starter --coordinator=ac -ORBInitialPort 5000 -ORBInitialHost lab22
java -cp client/bin/:. main_starter.main_starter --coordinator=coordi -ORBInitialPort 20000 -ORBInitialHost localhost
