#!/bin/bash
#java -cp starter/bin/:. main_starter.main_starter --name=$1 --coordinator=$2 -ORBInitialPort 5000 -ORBInitialHost lab22
java -cp starter/bin/:. main_starter.main_starter --name=$1 --coordinator=$2 --corba-fork-port=20000 --corba-fork-host=localhost -ORBInitialPort 20000 -ORBInitialHost localhost

