package starter;


/**
* starter/Starter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from starter.idl
* Samstag, 16. Mai 2015 21:52 Uhr MESZ
*/

public interface Starter extends StarterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Starter
