package worker;

/**
* worker/WorkerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from worker.idl
* Dienstag, 2. Juni 2015 17:45 Uhr MESZ
*/

public final class WorkerHolder implements org.omg.CORBA.portable.Streamable
{
  public worker.Worker value = null;

  public WorkerHolder ()
  {
  }

  public WorkerHolder (worker.Worker initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = worker.WorkerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    worker.WorkerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return worker.WorkerHelper.type ();
  }

}
