package worker;


/**
* worker/Worker.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from worker.idl
* Tuesday, 9 June 2015 10:05:15 o'clock CEST
*/

public interface Worker extends WorkerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Worker
