package monitor;


/**
* monitor/Monitor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monitor.idl
* Freitag, 5. Juni 2015 19:35 Uhr MESZ
*/

public interface Monitor extends MonitorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Monitor
