package worker;


/**
* worker/Worker.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl_files/worker.idl
* Tuesday, 12 May 2015 10:55:40 o'clock CEST
*/

public interface Worker extends WorkerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Worker
