package worker;


/**
* worker/Worker.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from worker.idl
* Samstag, 9. Mai 2015 17:50 Uhr MESZ
*/

public interface Worker extends WorkerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Worker
