
package sensorproxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "sensor", targetNamespace = "http://hawsensor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Sensor {


    /**
     * 
     * @param myself
     * @param displays
     * @return
     *     returns sensorproxy.BooleanArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://hawsensor/sensor/registerRequest", output = "http://hawsensor/sensor/registerResponse")
    public BooleanArray register(
        @WebParam(name = "myself", partName = "myself")
        String myself,
        @WebParam(name = "displays", partName = "displays")
        BooleanArray displays);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://hawsensor/sensor/getCoordinatorRequest", output = "http://hawsensor/sensor/getCoordinatorResponse")
    public String getCoordinator();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://hawsensor/sensor/signalUpdateRequest", output = "http://hawsensor/sensor/signalUpdateResponse")
    public void signalUpdate();

    /**
     * 
     * @param knownSensors
     * @param coordinatorUrl
     * @param assignedViews
     */
    @WebMethod
    @Action(input = "http://hawsensor/sensor/sendDataUpdateRequest", output = "http://hawsensor/sensor/sendDataUpdateResponse")
    public void sendDataUpdate(
        @WebParam(name = "known_sensors", partName = "known_sensors")
        AnyURIArray knownSensors,
        @WebParam(name = "assigned_views", partName = "assigned_views")
        AnyURIArray assignedViews,
        @WebParam(name = "coordinator_url", partName = "coordinator_url")
        String coordinatorUrl);

    /**
     * 
     * @param display
     */
    @WebMethod
    @Action(input = "http://hawsensor/sensor/removePermissionRequest", output = "http://hawsensor/sensor/removePermissionResponse")
    public void removePermission(
        @WebParam(name = "display", partName = "display")
        int display);

    /**
     * 
     * @param value
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://hawsensor/sensor/voteRequest", output = "http://hawsensor/sensor/voteResponse")
    public boolean vote(
        @WebParam(name = "value", partName = "value")
        long value);

}
